export const NET_INFO = "NET_INFO";

export const SET_TOKENS = "SET_TOKENS";

export const LOGIN_POST_API_REQUEST = "LOGIN_POST_API_REQUEST";
export const LOGIN_POST_API_SUCCESS = "LOGIN_POST_API_SUCCESS";
export const LOGIN_POST_API_FAILURE = "LOGIN_POST_API_FAILURE";

export const CHECKINOUT_GET_API_REQUEST = "CHECKINOUT_GET_API_REQUEST";
export const CHECKINOUT_GET_API_SUCCESS = "CHECKINOUT_GET_API_SUCCESS";
export const CHECKINOUT_GET_API_FAILURE = "CHECKINOUT_GET_API_FAILURE";

export const EMPLOYEE_DETAIL_GET_API_REQUEST = "EMPLOYEE_DETAIL_GET_API_REQUEST";
export const EMPLOYEE_DETAIL_GET_API_SUCCESS = "EMPLOYEE_DETAIL_GET_API_SUCCESS";
export const EMPLOYEE_DETAIL_GET_API_FAILURE = "EMPLOYEE_DETAIL_GET_API_FAILURE";

export const CHECKIN_POST_API_REQUEST = "CHECKIN_POST_API_REQUEST";
export const CHECKIN_POST_API_SUCCESS = "CHECKIN_POST_API_SUCCESS";
export const CHECKIN_POST_API_FAILURE = "CHECKIN_POST_API_FAILURE";

export const CHECKOUT_POST_API_REQUEST = "CHECKOUT_POST_API_REQUEST";
export const CHECKOUT_POST_API_SUCCESS = "CHECKOUT_POST_API_SUCCESS";
export const CHECKOUT_POST_API_FAILURE = "CHECKOUT_POST_API_FAILURE";

export const VIEW_REPORTS_API_REQUEST = "VIEW_REPORTS_API_REQUEST";
export const VIEW_REPORTS_API_SUCCESS = "VIEW_REPORTS_API_SUCCESS";
export const VIEW_REPORTS_API_FAILURE = "VIEW_REPORTS_API_FAILURE";

export const EVENTS_GET_API_REQUEST = "EVENTS_GET_API_REQUEST";
export const EVENTS_GET_API_SUCCESS = "EVENTS_GET_API_SUCCESS";
export const EVENTS_GET_API_FAILURE = "EVENTS_GET_API_FAILURE";

export const EVENT_DETAIL_GET_API_REQUEST = "EVENT_DETAIL_GET_API_REQUEST";
export const EVENT_DETAIL_GET_API_SUCCESS = "EVENT_DETAIL_GET_API_SUCCESS";
export const EVENT_DETAIL_GET_API_FAILURE = "EVENT_DETAIL_GET_API_FAILURE";


export const VIEW_TIMELY_REPORTS_GET_API_REQUEST = "VIEW_TIMELY_REPORTS_GET_API_REQUEST";
export const VIEW_TIMELY_REPORTS_GET_API_SUCCESS = "VIEW_TIMELY_REPORTS_GET_API_SUCCESS";
export const VIEW_TIMELY_REPORTS_GET_API_FAILURE = "VIEW_TIMELY_REPORTS_GET_API_FAILURE";
