// export const LOGIN = 'LOGIN';
export const LOGIN_POST_API_REQUEST = "LOGIN_POST_API_REQUEST";
export const LOGIN_POST_API_SUCCESS = "LOGIN_POST_API_SUCCESS";
export const LOGIN_POST_API_FAILURE = "LOGIN_POST_API_FAILURE";

export const CHECKINOUT_STATUS = "CHECKINOUT_STATUS";

export const EMPLOYEE_DETAIL_GET_API_REQUEST = "EMPLOYEE_DETAIL_GET_API_REQUEST";
export const EMPLOYEE_DETAIL_GET_API_SUCCESS = "EMPLOYEE_DETAIL_GET_API_SUCCESS";
export const EMPLOYEE_DETAIL_GET_API_FAILURE = "EMPLOYEE_DETAIL_GET_API_FAILURE";

export const CHECKIN_POST_API_REQUEST = "CHECKIN_POST_API_REQUEST";
export const CHECKIN_POST_API_SUCCESS = "CHECKIN_POST_API_SUCCESS";
export const CHECKIN_POST_API_FAILURE = "CHECKIN_POST_API_FAILURE";

export const CHECKOUT_POST_API_REQUEST = "CHECKOUT_POST_API_REQUEST";
export const CHECKOUT_POST_API_SUCCESS = "CHECKOUT_POST_API_SUCCESS";
export const CHECKOUT_POST_API_FAILURE = "CHECKOUT_POST_API_FAILURE";

export const VIEW_REPORTS_API_REQUEST = "VIEW_REPORTS_API_REQUEST";
export const VIEW_REPORTS_API_SUCCESS = "VIEW_REPORTS_API_SUCCESS";
export const VIEW_REPORTS_API_FAILURE = "VIEW_REPORTS_API_FAILURE";
